export const ARTICLE_GET_ALL_REQ = "ARTICLE_GET_ALL_REQ";
export const ARTICLE_GET_ALL_SUCCESS = "ARTICLE_GET_ALL_SUCCESS";
export const ARTICLE_GET_ALL_FAIL = "ARTICLE_GET_ALL_FAIL";
export const ARTICLE_GET_ALL_RESET = "ARTICLE_GET_ALL_RESET";

export const ARTICLE_GET_REQ = "ARTICLE_GET_REQ";
export const ARTICLE_GET_SUCCESS = "ARTICLE_GET_SUCCESS";
export const ARTICLE_GET_FAIL = "ARTICLE_GET_FAIL";
export const ARTICLE_GET_RESET = "ARTICLE_GET_RESET";

export const ARTICLE_GET_BY_USER_REQ = "ARTICLE_GET_BY_USER_REQ";
export const ARTICLE_GET_BY_USER_SUCCESS = "ARTICLE_GET_BY_USER_SUCCESS";
export const ARTICLE_GET_BY_USER_FAIL = "ARTICLE_GET_BY_USER_FAIL";
export const ARTICLE_GET_BY_USER_RESET = "ARTICLE_GET_BY_USER_RESET";

export const ARTICLE_POST_REQ = "ARTICLE_POST_REQ";
export const ARTICLE_POST_SUCCESS = "ARTICLE_POST_SUCCESS";
export const ARTICLE_POST_FAIL = "ARTICLE_POST_FAIL";
export const ARTICLE_POST_RESET = "ARTICLE_POST_RESET";

export const ARTICLE_UPDATE_REQ = "ARTICLE_UPDATE_REQ";
export const ARTICLE_UPDATE_SUCCESS = "ARTICLE_UPDATE_SUCCESS";
export const ARTICLE_UPDATE_FAIL = "ARTICLE_UPDATE_FAIL";
export const ARTICLE_UPDATE_RESET = "ARTICLE_UPDATE_RESET";

export const ARTICLE_DELETE_REQ = "ARTICLE_DELETE_REQ";
export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS";
export const ARTICLE_DELETE_FAIL = "ARTICLE_DELETE_FAIL";
export const ARTICLE_DELETE_RESET = "ARTICLE_DELETE_RESET";