export const REVIEW_POST_REQ = "REVIEW_POST_REQ";
export const REVIEW_POST_SUCCESS = "REVIEW_POST_SUCCESS";
export const REVIEW_POST_FAIL = "REVIEW_POST_FAIL";
export const REVIEW_POST_RESET = "REVIEW_POST_RESET";

export const REVIEW_UPDATE_REQ = "REVIEW_UPDATE_REQ";
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_SUCCESS";
export const REVIEW_UPDATE_FAIL = "REVIEW_UPDATE_FAIL";
export const REVIEW_UPDATE_RESET = "REVIEW_UPDATE_RESET";

export const REVIEW_DELETE_REQ = "REVIEW_DELETE_REQ";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";
export const REVIEW_DELETE_RESET = "REVIEW_DELETE_RESET";

export const REVIEW_GET_BY_USER_REQ = "REVIEW_GET_BY_USER_REQ";
export const REVIEW_GET_BY_USER_SUCCESS = "REVIEW_GET_BY_USER_SUCCESS";
export const REVIEW_GET_BY_USER_FAIL = "REVIEW_GET_BY_USER_FAIL";
export const REVIEW_GET_BY_USER_RESET = "REVIEW_GET_BY_USER_RESET";