export const USER_REGISTRATION_REQ = "USER_REGISTRATION_REQ";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";
export const USER_REGISTRATION_RESET = "USER_REGISTRATION_RESET";

export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATE_REQ = "USER_UPDATE_REQ";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_DELETE_REQ = "USER_DELETE_REQ";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

export const USER_GET_BY_ID_REQ = "USER_GET_BY_ID_REQ";
export const USER_GET_BY_ID_SUCCESS = "USER_GET_BY_ID_SUCCESS";
export const USER_GET_BY_ID_FAIL = "USER_GET_BY_ID_FAIL";
export const USER_GET_BY_ID_RESET = "USER_GET_BY_ID_RESET";

export const USER_BAN_REQ = "USER_BAN_REQ";
export const USER_BAN_SUCCESS = "USER_BAN_SUCCESS";
export const USER_BAN_FAIL = "USER_BAN_FAIL";
export const USER_BAN_RESET = "USER_BAN_RESET";

export const USER_UNBAN_REQ = "USER_UNBAN_REQ";
export const USER_UNBAN_SUCCESS = "USER_UNBAN_SUCCESS";
export const USER_UNBAN_FAIL = "USER_UNBAN_FAIL";
export const USER_UNBAN_RESET = "USER_UNBAN_RESET";